from __future__ import annotations


TRANSFER_STATUS_PENDING = "pending"
TRANSFER_STATUS_APPROVED = "approved"
TRANSFER_STATUS_REJECTED = "rejected"
ALLOWED_TRANSFER_STATUSES = {
    TRANSFER_STATUS_PENDING,
    TRANSFER_STATUS_APPROVED,
    TRANSFER_STATUS_REJECTED,
}
